topic = [
   "musician or group or band",
   "movie",
   "drama",
   "place",
   "politician",
   "athlete",
   "comedian",
   "actor",
   "actress",
   "city"
]

place = [
    "North America",
    "South America",
    "Asia",
    "Europe",
    "Africa",
    "Oceania"
]

cartoons = [
    "Naruto",
    "Dragon Ball Z",
    "One Piece",
    "Sailor Moon",
    "Pokémon",
    "Attack on Titan",
    "My Hero Academia",
    "Death Note",
    "Fullmetal Alchemist",
    "Bleach",
    "Neon Genesis Evangelion",
    "Cowboy Bebop",
    "Spirited Away",
    "Demon Slayer: Kimetsu no Yaiba",
    "Tokyo Ghoul",
    "One Punch Man",
    "Hunter x Hunter",
    "Fairy Tail",
    "JoJo's Bizarre Adventure",
    "Yu Yu Hakusho",
    "Mob Psycho 100",
    "Akira",
    "Your Name",
    "Sword Art Online",
    "Naruto Shippuden",
    "Death Parade",
    "Ghost in the Shell",
    "Ranma ½",
    "Black Clover",
    "Digimon",
    "Initial D",
    "Gurren Lagann",
    "Inuyasha",
    "Cardcaptor Sakura",
    "Gintama",
    "The Promised Neverland",
    "Parasyte -the maxim-",
    "Code Geass",
    "Trigun",
    "Rurouni Kenshin",
    "Kill la Kill",
    "Wolf's Rain",
    "Fate/stay night",
    "Berserk",
    "Tokyo Mew Mew",
    "Slam Dunk",
    "Detective Conan (Case Closed)",
    "Doraemon",
    "Astro Boy",
    "Kimba the White Lion (Jungle Emperor)",
    "Speed Racer (Mach GoGoGo)",
    "Heidi, Girl of the Alps",
    "Princess Knight (Ribon no Kishi)",
    "Sazae-san",
    "Lupin III",
    "Cyborg 009",
    "Gatchaman (Science Ninja Team Gatchaman)",
    "Dragon Ball",
    "Mazinger Z",
    "Candy Candy",
    "Getter Robo",
    "Space Battleship Yamato (Star Blazers)",
    "Tiger Mask",
    "GeGeGe no Kitaro",
    "Jungle Emperor Leo (Leo the Lion)",
    "Obake no Q-tarō",
    "Akage no Anne (Anne of Green Gables)",
    "Princess Sarah (A Little Princess Sara)",
    "Galaxy Express 999",
    "The Rose of Versailles (Versailles no Bara)",
    "Devilman",
    "Future Boy Conan",
    "Tetsujin 28-go (Gigantor)",
    "Urusei Yatsura (Lum Invader)",
    "The Adventures of Hutch the Honeybee",
    "Dokonjō Gaeru (The Gutsy Frog)",
    "Captain Tsubasa",
    "Maison Ikkoku",
    "Nausicaä of the Valley of the Wind",
    "Kinnikuman (Muscle Man)",
    "Science Ninja Team Gatchaman",
    "Lupin III: Part II",
    "Ganbare!! Tabuchi-kun!!",
    "Sally the Witch (Mahōtsukai Sarī)",
    "Yatterman",
    "Himitsu no Akko-chan (Secret Akko-chan)",
    "The Snow Queen",
    "Panda! Go, Panda!",
    "Space Pirate Captain Harlock",
    "Dokaben",
    "Tensai Bakabon",
    "Combattler V",
    "Casshan",
    "Cutie Honey",
    "Magical Princess Minky Momo",
    "Gekisou! Rubenkaiser",
    "Hana no Ko Lunlun"
]

patterns = [
    "illustration",
    "stencil art",
    "crayon",
    "crayon art",
    "chalk",
    "chalk art",
    "etching",
    "oil paintings",
    "ballpoint pen",
    "ballpoint pen art",
    "colored pencil",
    "watercolor",
    "Chinese watercolor",
    "pastels",
    "woodcut",
    "charcoal",
    "line drawing",
    "screen print",
    "photocollage",
    "storybook illustration",
    "newspaper cartoon",
    "vintage illustration from 1960s",
    "vintage illustration from 1980s",
    "anime style",
    "anime style, official art",
    "manga style",
    "Studio Ghibli style",
    "kawaii",
    "pixel art",
    "screenshot from SNES game",
    "vector illustration",
    "sticker art",
    "3D illustration",
    "cute 3D illustration in the style of Pixar",
    "Octane Render",
    "digital art",
    "2.5D",
    "isometric art",
    "ceramic art",
    "geometric art",
    "surrealism",
    "Dadaism",
    "metaphysical painting",
    "orphism",
    "cubism",
    "suprematism",
    "De Stijl",
    "futurism",
    "expressionism",
    "realism",
    "impressionism",
    "Art Nouveau",
    "baroque painting",
    "rococo painting",
    "mannerism painting",
    "bauhaus painting",
    "ancient Egyptian papyrus",
    "ancient Roman mosaic",
    "ukiyo-e",
    "painted in the style of Vincent van Gogh",
    "painted in the style of Alphonse Mucha",
    "painted in the style of Sophie Anderson",
    "painting by Vincent van Gogh",
    "painting by Alphonse Mucha",
    "painting by Sophie Anderson",  
]
