apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai_bot_app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 80
      containers:
      - image: ""
        env:
        - name: OPENAI_TOKEN
          valueFrom:
            secretKeyRef:
              name: openai-token
              key: '1'
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      serviceAccountName: ai_bot_app@yahayuta.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
